feat: Infra code for DO provider
Vizzuality/cms-scaffold pull request #11
Opened 2023-09-18 12:20 UTC by martintomas

Terraform code to run dockerized services (in this case Strapi and Client) within Digital Ocean provider.

PR also contains example of github workflow that handles build of docker images and its deploy to DO Apps.

2023-09-18 12:54 UTC, tiagojsag commented
I'll probably iterate on this once I use it (S3 dep needs to go, for example), but overall it seems like a good starting place! thanks for exploring and sharing this!

2023-09-18 12:55 UTC, tiagojsag approved these changes

2023-09-19 07:48 UTC, agnessa approved these changes

2023-09-19 07:51 UTC, tiagojsag requested changes
I just rebased your branch with the updated main, which now includes the AWS deployment with GH Secret management using TF. If you feel brave and have time, please copy-paste GH Secret management from it into your branch. If you have better things to do (and in case they aren't there already and I missed them) document what are the necessary GH secrets, and what they should achieve. Right now, a newcomer to your code will have to mentally reverse engineer your GH Action to understand what's missing

2023-09-20 08:23 UTC, martintomas commented
> I just rebased your branch with the updated main, which now includes the AWS deployment with GH Secret management using TF. If you feel brave and have time, please copy-paste GH Secret management from it into your branch. If you have better things to do (and in case they aren't there already and I missed them) document what are the necessary GH secrets, and what they should achieve. Right now, a newcomer to your code will have to mentally reverse engineer your GH Action to understand what's missing

I have tried to address all requested changes @tiagojsag so will merge this now, but feel free to let me know if you discover some other issues/improvements with this and I will do changes as separate PR.

2023-09-20 08:23 UTC, merged